#!/usr/bin/env node
// One-time script to generate base64-encoded 16x16 ICO files
// Run: node scripts/gen-icons.js
// Paste the output into src/icons.js

function makeIco(r, g, b) {
  const width = 16, height = 16;
  const pixelDataSize = width * height * 3;
  const andMaskSize = height * Math.ceil(width / 32) * 4;
  const bmpSize = 40 + pixelDataSize + andMaskSize;

  const buf = Buffer.alloc(6 + 16 + bmpSize, 0);
  let o = 0;

  // ICO header
  buf.writeUInt16LE(0, o); o += 2;       // reserved
  buf.writeUInt16LE(1, o); o += 2;       // type: ICO
  buf.writeUInt16LE(1, o); o += 2;       // image count

  // Image directory entry
  buf.writeUInt8(width, o); o++;
  buf.writeUInt8(height, o); o++;
  buf.writeUInt8(0, o); o++;             // color count
  buf.writeUInt8(0, o); o++;             // reserved
  buf.writeUInt16LE(1, o); o += 2;       // color planes
  buf.writeUInt16LE(24, o); o += 2;      // bits per pixel
  buf.writeUInt32LE(bmpSize, o); o += 4; // image data size
  buf.writeUInt32LE(22, o); o += 4;      // offset to image data

  // BITMAPINFOHEADER
  buf.writeUInt32LE(40, o); o += 4;          // header size
  buf.writeInt32LE(width, o); o += 4;
  buf.writeInt32LE(height * 2, o); o += 4;   // height*2 for ICO (XOR+AND)
  buf.writeUInt16LE(1, o); o += 2;           // color planes
  buf.writeUInt16LE(24, o); o += 2;          // bits per pixel
  buf.writeUInt32LE(0, o); o += 4;           // compression
  buf.writeUInt32LE(pixelDataSize, o); o += 4;
  buf.writeInt32LE(0, o); o += 4;
  buf.writeInt32LE(0, o); o += 4;
  buf.writeUInt32LE(0, o); o += 4;
  buf.writeUInt32LE(0, o); o += 4;

  // Pixel data: draw a filled circle, rows bottom-to-top (BMP convention)
  const cx = 7.5, cy = 7.5, radius = 6;
  for (let row = height - 1; row >= 0; row--) {
    for (let col = 0; col < width; col++) {
      const dx = col - cx, dy = row - cy;
      const inCircle = (dx * dx + dy * dy) <= radius * radius;
      buf[o++] = inCircle ? b : 30;  // Blue channel (or dark bg)
      buf[o++] = inCircle ? g : 30;  // Green channel
      buf[o++] = inCircle ? r : 30;  // Red channel
    }
  }

  // AND mask: all zeros (fully opaque)
  // already zeroed by Buffer.alloc

  return buf.toString('base64');
}

// Green: #22c55e → R=34, G=197, B=94
const ICON_IDLE = makeIco(34, 197, 94);

// Orange: #f59e0b → R=245, G=158, B=11
const ICON_ACTIVE = makeIco(245, 158, 11);

console.log(`// Auto-generated by scripts/gen-icons.js — do not edit manually
const ICON_IDLE = '${ICON_IDLE}';
const ICON_ACTIVE = '${ICON_ACTIVE}';
module.exports = { ICON_IDLE, ICON_ACTIVE };`);
